#pragma once

#include <stdint.h>

/* XXX: Comment out this line for a non-test network */
//#define GDW_TEST_NETWORK

#define GDW_TEST_NETWORK_VERSION                            83 // autogenerated

#define GDW_BLOCKCHAIN_DATABASE_VERSION                     uint64_t( 201 )

/**
 *  The address prepended to string representation of
 *  addresses.
 *
 *  Changing these parameters will result in a hard fork.
 */
#define GDW_ADDRESS_PREFIX                                  "G"
#define GDW_BLOCKCHAIN_SYMBOL                               "GDW"
#define GDW_BLOCKCHAIN_NAME                                 "Golden World"
#define GDW_BLOCKCHAIN_DESCRIPTION                          "Golden World For Future"
			
#define GDW_BLOCKCHAIN_PRECISION                            10000

#define GDW_BLOCKCHAIN_MAX_UIA_MARKET_FEE                   10000
#define GDW_BLOCKCHAIN_BLOCK_INTERVAL_SEC                   int64_t(10)
#define GDW_BLOCKCHAIN_BLOCKS_PER_HOUR                      ((60*60)/GDW_BLOCKCHAIN_BLOCK_INTERVAL_SEC)
#define GDW_BLOCKCHAIN_BLOCKS_PER_DAY                       (GDW_BLOCKCHAIN_BLOCKS_PER_HOUR*int64_t(24))
#define GDW_BLOCKCHAIN_BLOCKS_PER_YEAR                      (GDW_BLOCKCHAIN_BLOCKS_PER_DAY*int64_t(365))

#define GDW_BLOCKCHAIN_NUM_DELEGATES                        uint32_t(7)
#define GDW_MAX_DELEGATE_PAY_PER_BLOCK                      int64_t( 1.7 * GDW_BLOCKCHAIN_PRECISION ) 
#define GDW_BLOCKCHAIN_MAX_UNDO_HISTORY                     GDW_BLOCKCHAIN_BLOCKS_PER_HOUR

#define GDW_BLOCKCHAIN_REGISTER_ACCOUNT_FEE                 int64_t( 10 * GDW_BLOCKCHAIN_PRECISION ) 

#define GDW_BLOCKCHAIN_MAX_SLATE_SIZE                       (GDW_BLOCKCHAIN_NUM_DELEGATES + (GDW_BLOCKCHAIN_NUM_DELEGATES/10))
#define GDW_BLOCKCHAIN_MAX_MESSAGE_SIZE                     2048
#define GDW_BLOCKCHAIN_MAX_FREE_MESSAGE_SIZE                1024
#define GDW_BLOCKCHAIN_MAX_SOFT_MAX_MESSAGE_SIZE            40
#define GDW_BLOCKCHAIN_MIN_MESSAGE_FEE_COE                  100
#define GDW_BLOCKCHAIN_MAX_TRANSACTION_EXPIRATION_SEC       (60*60*24*2)
#define GDW_BLOCKCHAIN_MAX_MEMO_SIZE                        19 // bytes
#define GDW_BLOCKCHAIN_EXTENDED_MEMO_SIZE                   32 // bytes
#define GDW_BLOCKCHAIN_MAX_EXTENDED_MEMO_SIZE               (GDW_BLOCKCHAIN_MAX_MEMO_SIZE + GDW_BLOCKCHAIN_EXTENDED_MEMO_SIZE)

#define GDW_DEFAULT_TRANSACTION_FEE                         100 // 
#define GDW_DEFAULT_TRANSACTION_EXPIRATION_SEC              (60*60)
#define GDW_DEFAULT_CONTRACT_MARGIN                         (int64_t)10000000 * GDW_BLOCKCHAIN_PRECISION 

/**
 *  The maximum amount that can be issued for user assets.
 *
 *  10^18 / 2^63 < 1  however, to support representing all share values as a double in
 *  languages like java script, we must stay within the epsilon so
 *
 *  10^15 / 2^53 < 1 allows all values to be represented as a double or an int64
 */
#define GDW_BLOCKCHAIN_MAX_SHARES                           (int64_t(2100)*int64_t(1000)*int64_t(1000)*int64_t(1000)*int64_t(1000))

#define GDW_BLOCKCHAIN_MIN_NAME_SIZE                        1
#define GDW_BLOCKCHAIN_MAX_NAME_SIZE                        63
#define GDW_BLOCKCHAIN_MAX_NAME_DATA_SIZE                   (1024*64)

#define GDW_BLOCKCHAIN_MAX_SGDW_SYMBOL_SIZE                  8 // characters
#define GDW_BLOCKCHAIN_MIN_SYMBOL_SIZE                      3 // characters
#define GDW_BLOCKCHAIN_MAX_SYMBOL_SIZE                      12 // characters

#define GDW_BLOCKCHAIN_MIN_BURN_FEE                         GDW_BLOCKCHAIN_PRECISION * 1 // 1 

#ifdef GDW_TEST_NETWORK
#define GDW_BLOCKCHAIN_VOTE_UPDATE_PERIOD_SEC               10
#else
#define GDW_BLOCKCHAIN_VOTE_UPDATE_PERIOD_SEC               (60*60) // 1 hour
#endif

#define GDW_BLOCKCHAIN_MIN_FEEDS                            ((GDW_BLOCKCHAIN_NUM_DELEGATES/2) + 1)
#define GDW_BLOCKCHAIN_MINIMUM_SHORT_ORDER_SIZE             (GDW_BLOCKCHAIN_PRECISION*100)
#define GDW_BLOCKCHAIN_MIN_YIELD_PERIOD_SEC                 (60*60*24) // 24 hours
#define GDW_BLOCKCHAIN_MAX_YIELD_PERIOD_SEC                 (GDW_BLOCKCHAIN_BLOCKS_PER_YEAR * GDW_BLOCKCHAIN_BLOCK_INTERVAL_SEC) // 1 year

#ifdef GDW_TEST_NETWORK
#define GDW_BLOCKCHAIN_MAX_SHORT_PERIOD_SEC                 (2*60*60) // 2 hours
#else
#define GDW_BLOCKCHAIN_MAX_SHORT_PERIOD_SEC                 (30*24*60*60) // 1 month
#endif
#define GDW_BLOCKCHAIN_MAX_SHORT_APR_PCT                    (uint64_t(50))

#define GDW_BLOCKCHAIN_MCALL_D2C_NUMERATOR                  1
#define GDW_BLOCKCHAIN_MCALL_D2C_DENOMINATOR                2

// TODO: This stuff only matters for propagation throttling; should go somewhere else
#define GDW_BLOCKCHAIN_DEFAULT_RELAY_FEE                    1 // 
#define GDW_BLOCKCHAIN_MAX_TRX_PER_SECOND                   1000  // (1000)
#define GDW_BLOCKCHAIN_MAX_PENDING_QUEUE_SIZE               10000 // (GDW_BLOCKCHAIN_MAX_TRX_PER_SECOND * GDW_BLOCKCHAIN_BLOCK_INTERVAL_SEC)

#define GDW_BLOCKCHAIN_REVALIDATE_MAX_TRX_COUNT             (GDW_BLOCKCHAIN_MAX_TRX_PER_SECOND * GDW_BLOCKCHAIN_BLOCK_INTERVAL_SEC)


// for contract
#define  CONTRACT_ADDRESS_PREFIX "c" 
#define  SCRIPT_ID_PREFIX "s" 
#define  MULTI_ADDRESS_PREFIX "M"


#define  CONTRACT_MAX_BYTECODE_SIZE   (1 * 1024 * 1024)  //just set to the limit of block size
#define  CONTRACT_MAX_NAME_SIZE  32 
#define  CONTRACT_MAX_DESCRIPTION_SIZE  256
#define  LIMIT_PRICE 1
#define  LIMIT_PER_AMOUNT 1000
#define  CONTRACT_PARAM_MAX_LEN  1024

#define  CONTRACT_OFFLINE_LIMIT_MAX     (1024*1024*1024) 
#define  CONTRACT_TESTING_LIMIT_MAX     (1024*1024*1024) 

// for event
#define  EVENT_PARAM_MAX_LEN  1024
#define  EVENT_TYPE_MAX_LEN   256

#define GDW_BLOCKCHAIN_FREESIGNATURE_LIMIT	10
#define GDW_BLOCKCHAIN_MAX_SIGNAGTURE_NUM   1000
#define GDW_BLOCKCHAIN_EXTRA_SIGNATURE_FEE  1000
#define GDW_BLOCKCHAIN_TRANSACTION_MAX_DEPOSIT_NUM 100

